version: '3.1'
services:
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4_local
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: example@example.com
      PGADMIN_DEFAULT_PASSWORD: example
    ports:
      - 5050:80